name = "Mediathekview"
license = "MIT"

[author]
    name = "Alexander Finkhäuser"
    homepage = "http://mediathekview.de"
    
[original]
    name = "Göran Svensson"
    homepage = "http://appernetic.github.io"