language: go
sudo: true
dist: trusty

go:
  - master

install:
  - go get github.com/magefile/mage
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - mage vendor
  - HUGO_BUILD_TAGS=extended mage install
# - go get github.com/spf13/hugo
#  - sudo apt-get --yes install snapd
#  - sudo snap install hugo
#  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#  - brew install hugo
#  - wget https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1-64bit.deb
#  - sudo dpkg -i hugo_0.18.1-64bit.deb

script:
  - hugo version
  - hugo check
  - hugo -v

