sudo: true
dist: trusty
install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo
#  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#  - brew install hugo
#  - wget https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1-64bit.deb
#  - sudo dpkg -i hugo_0.18.1-64bit.deb

script:
  - /snap/bin/hugo version
  - /snap/bin/hugo check
  - /snap/bin/hugo -v

