language: go
sudo: true
dist: trusty

go:
  - master

install:
  - echo URL zum Download $(curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest"| grep "url"| grep "Linux-64bit.deb"|cut -d'"' -f4)
  - wget $(curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest"| grep "url"| grep "Linux-64bit.deb"|cut -d'"' -f4) -O hugo.deb
  - sudo dpkg -i hugo.deb
# - go get github.com/spf13/hugo
#  - sudo apt-get --yes install snapd
#  - sudo snap install hugo
#  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
#  - brew install hugo
#  - wget https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1-64bit.deb
#  - sudo dpkg -i hugo_0.18.1-64bit.deb

script:
  - hugo version
  - hugo check
  - hugo -v

