baseurl = "https://mediathekview.de"
title = "MediathekView"
languageCode = "de-de"
DefaultContentLanguage = "de"
theme = "mediathekview"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "Tags"

[author]
    name = "Mediathekview"
    email = "support@mediathekview.de"

[params]
    BrandImage = "/images/MediathekView.png" #top header brand image.
    brand = "Mediathekview" # brand image alt text.
    topline = "Die offizelle MediathekView Homepage"
    footline = ""
    
    copyright = "(c) 2016 Copyright by Mediathekview Team"
    title = "MediathekView" # Site title

    # Show a sidebar menu
    showRightSidebar = true


    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Sidebar social links.
    github = "mediathekview" # Your Github profile ID
    #youtube = ""  # Your Youtube channel ID
    flattr = "mediathekview"  # populate with your flattr uid
    
    
    [[menu.main]]
    name = "Neuigkeiten"
    title = "Neuigkeiten"
    pre = ""
    weight = 1
    url = "/news"
    
    [[menu.main]]
    name = "Changelogs"
    title = "Changelogs"
    pre = ""
    weight = 2
    url = "/changelog"
    
    [[menu.footer]] 
    name = "Impressum"
    pre = "<i>-</i>"
    weight = 1
    url = "/impressum/"

    [[menu.footer]]
    name = "Kontakt"
    weight = 1
    url = "/kontakt/"

[blackfriday]
    hrefTargetBlank = true
    latexDashes = true
    plainIdAnchors = true

  #custom_css = ["/css/css.css"]
		
