baseurl = "https://mediathekview.de"
title = "MediathekView"
languageCode = "de-de"
DefaultContentLanguage = "de"
theme = "mediathekview"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "Tags"

[author]
    name = "Alexander Finkhäuser"
    email = "alex@elaon.de"

[params]
    BrandImage = "/images/MediathekView.png" #top header brand image.
    brand = "Mediathekview" # brand image alt text.
    topline = "Die offizelle MediathekView Homepage"
    footline = "Erstellt mit <i class='fa fa-heart'></i>"
    
    copyright = "(c) 2016 Copyright by Mediathekview Team"
    title = "MediathekView" # Site title

    # Show a sidebar menu
    showRightSidebar = true

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "home"
    
    startpage = "index"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Sidebar social links.
    github = "mediathekview" # Your Github profile ID
    #bitbucket = "" # Your Bitbucket profile ID
    #linkedin = "" # Your LinkedIn profile ID (from public URL)
    #googleplus = "" # Your Google+ profile ID
    #facebook = "" # Your Facebook profile ID
    #twitter = "" # Your Twitter profile ID
    #youtube = ""  # Your Youtube channel ID
    flattr = "mediathekview"  # populate with your flattr uid
    
    
    [[menu.main]]
    name = "Neuigkeiten"
    title = "Neuigkeiten"
    pre = ""
    weight = 1
    url = "/news"
    
    [[menu.footer]] # add  links to the bottom right corner.
    name = "Impressum"
    pre = "<i>-</i>"
    weight = 1
    url = "/impressum/"

    [[menu.footer]]
    name = "Kontakt"
    weight = 2
    url = "/kontakt/"

[blackfriday]
    hrefTargetBlank = true
    latexDashes = true
    plainIdAnchors = true

    # Menus
    # If you want active menu items highlighted for internal pages don't add them here, they need to be added in each files front matter.
    # like this:
    #[menu]
    #     [menu.main]
    #        name = "Showcase"
    #        weight = 3
    #        identifier = "showcase"

  #custom_css = ["/css/css.css"]
		
